//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from MockCallSetup.Arities.tt — edit the template, not this file,
//     then regenerate with: dotnet t4 MockCallSetup.Arities.tt
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using TestFramework.Mock.Artifacts;

namespace TestFramework.Mock;

public sealed partial class MockCallSetup<TService, TResult>
    where TService : class
{
    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1>(Func<T1, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1>(Func<T1, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1>(Func<T1, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2>(Func<T1, T2, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2>(Func<T1, T2, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2>(Func<T1, T2, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3>(Func<T1, T2, T3, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3>(Func<T1, T2, T3, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3>(Func<T1, T2, T3, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3, T4>(Func<T1, T2, T3, T4, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3, T4>(Func<T1, T2, T3, T4, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3, T4>(Func<T1, T2, T3, T4, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3, T4, T5>(Func<T1, T2, T3, T4, T5, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3, T4, T5>(Func<T1, T2, T3, T4, T5, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3, T4, T5>(Func<T1, T2, T3, T4, T5, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3, T4, T5, T6>(Func<T1, T2, T3, T4, T5, T6, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3, T4, T5, T6>(Func<T1, T2, T3, T4, T5, T6, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3, T4, T5, T6>(Func<T1, T2, T3, T4, T5, T6, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3, T4, T5, T6, T7>(Func<T1, T2, T3, T4, T5, T6, T7, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3, T4, T5, T6, T7>(Func<T1, T2, T3, T4, T5, T6, T7, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3, T4, T5, T6, T7>(Func<T1, T2, T3, T4, T5, T6, T7, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6))));
        return this;
    }

    /// <summary>
    /// The result is computed from the call's arguments. The lambda's parameter types are checked
    /// against the mocked method where the setup is declared.
    /// </summary>
    public MockCallSetup<TService, TResult> Returns<T1, T2, T3, T4, T5, T6, T7, T8>(Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.SetResponse((arguments, _) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7)));
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService, TResult> Compute<T1, T2, T3, T4, T5, T6, T7, T8>(Func<T1, T2, T3, T4, T5, T6, T7, T8, MockArtifacts, TResult> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.SetResponse((arguments, artifacts) => compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7), artifacts));
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService, TResult> ProducesArtifact<T1, T2, T3, T4, T5, T6, T7, T8>(Func<T1, T2, T3, T4, T5, T6, T7, T8, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7))));
        return this;
    }

}

public sealed partial class MockCallSetup<TService>
    where TService : class
{
    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1>(Action<T1> action)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1>(Action<T1, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1>(Func<T1, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2>(Action<T1, T2> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2>(Action<T1, T2, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2>(Func<T1, T2, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3>(Action<T1, T2, T3> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3>(Action<T1, T2, T3, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3>(Func<T1, T2, T3, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3, T4>(Action<T1, T2, T3, T4> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3, T4>(Action<T1, T2, T3, T4, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3, T4>(Func<T1, T2, T3, T4, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3, T4, T5>(Action<T1, T2, T3, T4, T5> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3, T4, T5>(Action<T1, T2, T3, T4, T5, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3, T4, T5>(Func<T1, T2, T3, T4, T5, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3, T4, T5, T6>(Action<T1, T2, T3, T4, T5, T6> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3, T4, T5, T6>(Action<T1, T2, T3, T4, T5, T6, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3, T4, T5, T6>(Func<T1, T2, T3, T4, T5, T6, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3, T4, T5, T6, T7>(Action<T1, T2, T3, T4, T5, T6, T7> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3, T4, T5, T6, T7>(Action<T1, T2, T3, T4, T5, T6, T7, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3, T4, T5, T6, T7>(Func<T1, T2, T3, T4, T5, T6, T7, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6))));
        return this;
    }

    /// <summary>
    /// Runs on every matching call, with the call's arguments.
    /// </summary>
    public MockCallSetup<TService> Callback<T1, T2, T3, T4, T5, T6, T7, T8>(Action<T1, T2, T3, T4, T5, T6, T7, T8> action)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.SetResponse((arguments, _) =>
        {
            action(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7));
            return null;
        });
        return this;
    }

    /// <summary>
    /// The primitive form: the call's arguments plus the artifact channel behind them.
    /// </summary>
    public MockCallSetup<TService> Compute<T1, T2, T3, T4, T5, T6, T7, T8>(Action<T1, T2, T3, T4, T5, T6, T7, T8, MockArtifacts> compute)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.SetResponse((arguments, artifacts) =>
        {
            compute(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7), artifacts);
            return null;
        });
        return this;
    }

    /// <summary>
    /// The artifact is built from the call's arguments, captured at call time; publishes only when
    /// the call completes, and stacks.
    /// </summary>
    public MockCallSetup<TService> ProducesArtifact<T1, T2, T3, T4, T5, T6, T7, T8>(Func<T1, T2, T3, T4, T5, T6, T7, T8, MockArtifact> produce)
    {
        this.ValidateArgumentTypes(typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5), typeof(T6), typeof(T7), typeof(T8));
        this.AddArtifactProducer((arguments, artifacts) => artifacts.Publish(produce(Argument<T1>(arguments, 0), Argument<T2>(arguments, 1), Argument<T3>(arguments, 2), Argument<T4>(arguments, 3), Argument<T5>(arguments, 4), Argument<T6>(arguments, 5), Argument<T7>(arguments, 6), Argument<T8>(arguments, 7))));
        return this;
    }

}
