//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from MockExt.Arities.tt — edit the template, not this file,
//     then regenerate with: dotnet t4 MockExt.Arities.tt
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Threading.Tasks;

using TestFramework.Core.Variables;

namespace TestFramework.Mock;

public static partial class MockExt
{
    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, TService, TResult>(
        VariableReference<T1> argument1,
        Func<T1, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, service)),
            [argument1]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, TService, TResult>(
        VariableReference<T1> argument1,
        Func<T1, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, service),
            [argument1]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, TService>(
        VariableReference<T1> argument1,
        Func<T1, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, service),
            [argument1]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        Func<T1, T2, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, service)),
            [argument1, argument2]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        Func<T1, T2, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, service),
            [argument1, argument2]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        Func<T1, T2, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, service),
            [argument1, argument2]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        Func<T1, T2, T3, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, service)),
            [argument1, argument2, argument3]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        Func<T1, T2, T3, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, service),
            [argument1, argument2, argument3]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        Func<T1, T2, T3, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, service),
            [argument1, argument2, argument3]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        Func<T1, T2, T3, T4, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, service)),
            [argument1, argument2, argument3, argument4]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        Func<T1, T2, T3, T4, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, T4, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        Func<T1, T2, T3, T4, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        Func<T1, T2, T3, T4, T5, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, service)),
            [argument1, argument2, argument3, argument4, argument5]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        Func<T1, T2, T3, T4, T5, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, T4, T5, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        Func<T1, T2, T3, T4, T5, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        Func<T1, T2, T3, T4, T5, T6, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, service)),
            [argument1, argument2, argument3, argument4, argument5, argument6]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        Func<T1, T2, T3, T4, T5, T6, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, T4, T5, T6, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        Func<T1, T2, T3, T4, T5, T6, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, T7, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        Func<T1, T2, T3, T4, T5, T6, T7, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, service)),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, T7, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        Func<T1, T2, T3, T4, T5, T6, T7, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, T4, T5, T6, T7, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        Func<T1, T2, T3, T4, T5, T6, T7, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7]);
    }

    /// <summary>
    /// A trigger that resolves the service from the run's mock host and calls it with arguments
    /// bound from run variables — a named variable is declared as the step's input, so the IO
    /// contract carries the dependency.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, T7, T8, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        VariableReference<T8> argument8,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TService, TResult> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(argument8);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => Task.FromResult(call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, argument8.GetValue(variables)!, service)),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7, argument8]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns; the step's result is what the task yielded.
    /// </summary>
    public static MockHostCallTrigger<TService, TResult> Host<T1, T2, T3, T4, T5, T6, T7, T8, TService, TResult>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        VariableReference<T8> argument8,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TService, Task<TResult>> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(argument8);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService, TResult>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, argument8.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7, argument8]);
    }

    /// <summary>
    /// A trigger that calls the hosted service with arguments bound from run variables and awaits
    /// the task it returns, for a call that yields no value.
    /// </summary>
    public static MockHostCallTrigger<TService> Host<T1, T2, T3, T4, T5, T6, T7, T8, TService>(
        VariableReference<T1> argument1,
        VariableReference<T2> argument2,
        VariableReference<T3> argument3,
        VariableReference<T4> argument4,
        VariableReference<T5> argument5,
        VariableReference<T6> argument6,
        VariableReference<T7> argument7,
        VariableReference<T8> argument8,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TService, Task> call)
        where TService : class
    {
        ArgumentNullException.ThrowIfNull(argument1);
        ArgumentNullException.ThrowIfNull(argument2);
        ArgumentNullException.ThrowIfNull(argument3);
        ArgumentNullException.ThrowIfNull(argument4);
        ArgumentNullException.ThrowIfNull(argument5);
        ArgumentNullException.ThrowIfNull(argument6);
        ArgumentNullException.ThrowIfNull(argument7);
        ArgumentNullException.ThrowIfNull(argument8);
        ArgumentNullException.ThrowIfNull(call);

        return new MockHostCallTrigger<TService>(
            (variables, service) => call(argument1.GetValue(variables)!, argument2.GetValue(variables)!, argument3.GetValue(variables)!, argument4.GetValue(variables)!, argument5.GetValue(variables)!, argument6.GetValue(variables)!, argument7.GetValue(variables)!, argument8.GetValue(variables)!, service),
            [argument1, argument2, argument3, argument4, argument5, argument6, argument7, argument8]);
    }

}
